name: Cloudflared android build

on:
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: "cloudflare/cloudflared"

    - name: Build
      run: |
          sed -i 's/linux/android/g' Makefile
          make cloudflared

    - uses: actions/upload-artifact@v2
      with:
        name: cloudflared
        path: cloudflared
