name: code-server
on: workflow_dispatch

jobs:
  code-server:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/universal:linux
    services:
      code-server:
        image: ghcr.io/linuxserver/code-server:latest
        env:
          PUID: 1000
          PGID: 1000
          TZ: Asia/Seoul
          PASSWORD: ${{ secrets.PASSWORD }}
        ports:
          - 8443:8443
    steps:
      - name: sleep
        run: sleep 10
      - run: sudo curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
      - run: sudo chmod a+x cloudflared
      - run: sudo ./cloudflared update
      - run: sudo ./cloudflared tunnel --url http://localhost:8443 &
      - name: sleep
        run: sleep 21600
