name: code-server
on: workflow_dispatch

jobs:
  code-server:
    runs-on: macos-11
    steps:
      - run: brew install code-server
      - run: nohup code-server --port 8443 --auth password --disable-telemetry &
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
      - run: curl localhost:8443
      - run: brew install cloudflare/cloudflare/cloudflared
      - run: cloudflared tunnel --url http://localhost:8443 --logfile "/tmp/cloudflared.log" &
      - name: show result link
        run: sleep 10 && cat /tmp/cloudflared.log && sudo rm -rf /tmp/cloudflared.log
      - name: sleep
        run: sleep 36000
