# This is a basic workflow to help you get started with Actions

name: delete workflow

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo name ex) keepsobp/keepsobp'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.event.inputs.repo }}
          retain_days: 0
          keep_minimum_runs: 0
