name: discodo test
on: [workflow_dispatch]

jobs:
  test1:
    runs-on: ubuntu-latest
    services:
      discodo:
        image: kijk2869/discodo:release-3.0.3
        ports:
          - 8000:8000
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: kspactions/workflows/cloudflared@main
        with:
          args: version

      - run: nohup cloudflared tunnel --url=http://127.0.0.1:8000 &

      - run: sleep 358m

      - uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 0.01
