name: egodocker
on: workflow_dispatch

jobs:
  egodocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nyanarchive/osu-lazer-server
          submodules: "recursive"
      - run: mv OsuLazerServer/Dockerfile Dockerfile
      - name: change mirror
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "rus.nerinyan.moe"
          replace: "api.nerinyan.moe"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/nyanactions/test/osu-lazer-server
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
