name: docker-ronni

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  repository: 'aticie/ronnia'
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: ghcr.io/nyanactions/ronni
            - name: Login to Github Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - run: |
                  rm Dockerfile
                  wget -O Dockerfile https://raw.githubusercontent.com/NyanActions/test/main/docker-ronni
            - name: Build and publish
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
