name: egodocker
on: push

jobs:
  egodocker:
    runs-on: ubuntu-latest
    steps:
      - run: git clone "http://46.39.239.70:32333/dhcpcd9/osu-lazer-server.git" egolazer
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/nyanactions/test/egolazer
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: egolazer/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
