name: endeavouros w3

on:
  workflow_dispatch:
     inputs:
       year:
         required: true

jobs:
  web3:
    runs-on: ubuntu-latest
    steps:
      - run: |
          URL=$(curl -s https://api.github.com/repos/endeavouros-team/ISO/releases/tags/1-EndeavourOS-ISO-releases-archive | grep browser_download_url | grep 'endeavouros-${{ github.event.inputs.year }}' | cut -d '"' -f 4)
          echo $URL
          echo "$URL" >> web3.txt
          wget -L -i web3.txt -P ./${{ github.event.inputs.year }}/ > /dev/null 2>&1
      - uses: web3-storage/add-to-web3@v1
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: ${{ github.event.inputs.year }}

      - run: echo https://${{ steps.web3.outputs.cid }}.ipfs.infura-ipfs.io
