name: KeyOverlay
on: workflow_dispatch

jobs:
  code-server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "blondazz/keyoverlay"
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Build
        run: sudo dotnet build --configuration Release -o /build
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: KeyOverlay-${{ matrix.os }}
          path: build/
