name: KeyOverlay
on: workflow_dispatch

jobs:
  code-server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "blondazz/keyoverlay"
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore -o /build
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: KeyOverlay
          path: build/
