name: lazer-patcher
on: workflow_dispatch

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: git clone http://git.dhcpcd.xyz/dhcpcd9/Patcher.git patch
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "lazer.dhcpcd.xyz"
          replace: "lazer.aeong.one"
      - name: Build
        run: cd patch && dotnet build --configuration Release -o build/
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: lazer-patcher-linux
          path: patch/build/

  macos:
    runs-on: macos-latest
    steps:
      - run: git clone http://git.dhcpcd.xyz/dhcpcd9/Patcher.git patch
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - run: sed -i '' 's/lazer.dhcpcd.xyz/lazer.aeong.one/' patch/osu-lazer-dll-patcher/Program.cs
      - name: Build
        run: cd patch && dotnet build --configuration Release -o build/
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: lazer-patcher-macos
          path: patch/build/

  windows:
    runs-on: windows-latest
    steps:
      - run: git clone http://git.dhcpcd.xyz/dhcpcd9/Patcher.git patch
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - run: ((Get-Content -path patch/osu-lazer-dll-patcher/Program.cs -Raw) -replace 'lazer.dhcpcd.xyz','lazer.aeong.one') | Set-Content -Path patch/osu-lazer-dll-patcher/Program.cs
      - name: Build
        run: cd patch && dotnet build --configuration Release -o build/
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: lazer-patcher-winos
          path: patch/build/

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "ppy/osu"
          submodules: "recursive"
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "/https.*ppy.*sh/gm"
          replace: "lazer.aeong.one"
          include: "osu.Game/Online/ProductionEndpointConfiguration.cs"
          regex: true
      - name: Build
        run: dotnet build osu.Android --configuration Release -p:PublishSingleFile=true --no-self-contained -r android-arm64 -o build/
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: lazer-patcher-linux
          path: patch/build/


