name: obs coreaudio
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download itunes
        run: wget https://www.apple.com/itunes/download/win64 -O itunes.zip

      - name: get coreaudio
        run: ls && unzip itunes.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: coreaudio
          files: |
              AppleApplicationSupport64.msi
              AppleApplicationSupport.msi
          body: "not a virus! Check workflow here: https://github.com/KSPActions/test/blob/main/.github/workflows/obscoreaudio.yml"
