name: Android CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: osudroid/osu-droid
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build && ls 
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk-build
        path: ./
