name: Update winget package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        

jobs:
  wingetcreate-update:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Download & Run wingetcreate update
        run: |
          curl https://aka.ms/wingetcreate/preview -L --output wingetcreate.exe
          wingetcreate.exe update Peppy.Osu! -u https://github.com/ppy/osu/releases/download/${{ github.event.inputs.version }}/install.exe -v ${{ github.event.inputs.version }} -t ${{ secrets.GH_TOKEN }} -s true
