name: Update osu!lazer winget package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        

jobs:
  wingetcreate-update:
    runs-on: windows-latest

    steps:
      - name: Download & Run wingetcreate update
        shell: cmd
        run: |
          curl https://github.com/microsoft/winget-create/releases/latest/download/wingetcreate-self-contained.exe -L --output wingetcreate.exe
          wingetcreate.exe update Peppy.Osu! -u https://github.com/ppy/osu/releases/download/${{ github.event.inputs.version }}/install.exe -v ${{ github.event.inputs.version }} -t ${{ secrets.GH_TOKEN }} -s
