name: Discord Bridge build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: Jan0660/Taco
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build DiscordBridge/DiscordBrdge.csproj -o ./build
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: DiscordBridge
        path: build/
