# https://github.com/KSPActions/reverse-rdssh-actions
# debugging only - @keepsobp
name: ubuntu-rdp

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Change runner password
      run: |
         sudo apt-get update 
         echo 'runner:${{ secrets.PASSWORD }}' | sudo chpasswd
         echo 'runneradmin:${{ secrets.PASSWORD }}' | sudo chpasswd

    - name: Install desktop environment 
      run: |
        sudo apt-get install xfce4 xfce4-terminal -y 

    - name: Install xrdp
      run: |
        sudo apt-get install xrdp
        sudo adduser xrdp ssl-cert
        echo xfce4-session > ~/.xsession
        sudo service xrdp restart     

    - name: Setup Cloudflare Tunnel
      uses: AnimMouse/setup-cloudflared@v1
      with:
        cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIAL }}
        cloudflare_tunnel_configuration: ${{ secrets.CLOUDFLARE_TUNNEL_CONFIGURATION }}
        cloudflare_tunnel_id: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
      
    - name: Shutdown and view logs of Cloudflare Tunnel
      if: always()
      uses: AnimMouse/setup-cloudflared/shutdown@v1
