name: web3 upload bruh

on:
  push:
  workflow_dispatch:
  paths:
    - "web3.txt"

jobs:
  web3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget --input-file=web3.txt -P ./ghactions/ > /dev/null 2>&1
      - uses: web3-storage/add-to-web3@v1
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: 'ghactions'
          wrap_with_directory: true

      - run: echo https://${{ steps.web3.outputs.cid }}.ipfs.astyanax.io
