name: web3 upload bruh

on:
  push:
     branches:
       - "main"
     paths:
       - "web3.txt"
       - ".github/workflows/web3.yml"
       - "curl.sh"
  workflow_dispatch:

jobs:
  web3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod a+x curl.sh && ./curl.sh
      - uses: web3-storage/add-to-web3@v1
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: 'ghactions'

      - run: echo https://${{ steps.web3.outputs.cid }}.ipfs.infura-ipfs.io
