# https://github.com/KSPActions/reverse-rdssh-actions
# debugging only - @keepsobp

name: windows-rdp

on: workflow_dispatch

jobs:
  windows-rdp:
    runs-on: windows-latest
    continue-on-error: true

    steps:
    - name: Download Cloudflared
      run: Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.PASSWORD }}" -Force)
      
    - name: config
      run: |
        mkdir "~/.cloudflared";
        $secretFile = New-Item "~/.cloudflared/config.yaml"; 
        $encodedBytes = [System.Convert]::FromBase64String($env:SECRET_DATA); 
        Set-Content $secretFile -Value $encodedBytes -AsByteStream;
        Get-Content "~/.cloudflared/config.yaml"
      shell: pwsh
      env:
        SECRET_DATA: ${{ secrets.CONFIG }}

    - name: tunnel
      run: |
        $secretFile = New-Item "~/.cloudflared/00ca6bd6-919d-474f-978a-0bd6d3444ff3.json"; 
        $encodedBytes = [System.Convert]::FromBase64String($env:SECRET_DATA); 
        Set-Content $secretFile -Value $encodedBytes -AsByteStream;
      shell: pwsh
      env:
        SECRET_DATA: ${{ secrets.TUNNEL }}

    - name: Create Tunnel
      run: Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel run"
      
    - run: Start-Sleep -s 10
    
    - run: Get-Content C:\cloudflared.log

    - run: Start-Sleep -s 21600
    
   
